spring.application.name=QuestionHub

# MySQL Bağlantı Ayarları
spring.datasource.url=${MY_DB_URL}
spring.datasource.username=${MY_DB_USERNAME}
spring.datasource.password=${MY_DB_PASSWORD}

# JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true

# JWT Ayarları
jwt.secret=${MY_JWT_SECRET_KEY}
# Token süresi long tipinde ve milisaniye (ms) cinsinden hesaplanır
jwt.refresh-token-expiration=86400000
jwt.access-token-expiration=900000